#+TITLE: Enrollment
#+OPTIONS: toc:nil num:nil

* Hours
Thousand Oaks Daycare is open from 8AM-5:30PM, Monday through
Friday.

* Holidays

- 2014-09-01 Mon Labor Day
- 2014-10-13 Mon Indigenous People’s Day
- 2014-11-26 Wed → 2014-11-28 Fri Thanksgiving Week
- 2014-12-19 Fri → 2015-01-02 Fri Winter Break (closed after 2014-12-18 Thu reopens on 2015-01-05 Mon)
- 2015-01-19 Mon Martin Luther King Day
- 2015-02-16 Mon President’s Day
- 2015-04-03 Fri  Easter Weekend
- 2015-05-25 Mon Memorial Day
- 2015-07-04 Mon 4^{th} of July
- Summer Vacation – TBD
- 2015-09-07 Mon Labor Day
- 2015-10-12 Mon Indigenous People’s Day
- Winter Break – TBD

If you need care during one of the holidays, I may be able to provide care if it has been arranged in advance.

Additionally: 5 sick days per year only taken if too ill/contagious to provide care


* Monthly Fees

- 2 days / week = 1100
- 3 days / week = 1250
- 4 days / week = 1400
- 5 days / week = 1550

I currently do not provide half days. Some parents drop their children off a little later or pick them up earlier, which is fine.

* Forms

The contract is [[../data/Thousand%20Oaks%20Childcare.pdf][available for download]].
