#+TITLE: Enrollment
#+OPTIONS: toc:nil num:nil

* Hours
Thousand Oaks Daycare is open from 8AM-5:30PM, Monday through
Friday.

* Holidays

- 2015-12-18 Fri → 2016-01-01 Fri Winter Break  (closed after 2015-12-17 Thu reopens on 2016-01-04 Mon)
- 2016-01-18 Mon Martin Luther King Day
- 2016-02-15 Mon President’s Day
- 2016-03-25 Fri  Easter Weekend
- 2016-05-30 Mon Memorial Day
- 2016-07-04 Mon 4^{th} of July
- 2016-07-18 Mon → 2016-07-29 Fri Summer Vacation
- 2016-09-05 Mon Labor Day
- 2016-10-10 Mon Indigenous People’s Day
- 2016-11-21 Mon → 2016-11-25 Fri Thanksgiving Week
- Winter Break — TBD

If you need care during one of the holidays, I may be able to provide care if it has been arranged in advance.

Additionally: 5 sick days per year only taken if too ill/contagious to provide care


* Monthly Fees

- 2 days / week = 1250
- 3 days / week = 1400
- 4 days / week = 1550
- 5 days / week = 1700


- extra days : 90

I currently do not provide half days. Some parents drop their children off a little later or pick them up earlier, which is fine.

* Forms

The contract is [[../data/Thousand%20Oaks%20Childcare.pdf][available for download]].
