#+TITLE: Enrollment
#+OPTIONS: toc:nil num:nil

* Hours
Thousand Oaks Daycare is open from 8AM-5:30PM, Monday through
Friday.

* Holidays

- 2015-08-17 Monday → 2015-08-28 Friday : Summer vacation
- 2015-09-07 Mon Labor Day
- 2015-10-12 Mon Indigenous People’s Day
- 2015-11-25 Wed → 2015-11-27 Fri Thanksgiving Week
- 2015-12-18 Fri → 2016-01-01 Fri Winter Break  (closed after 2015-12-18 Thu reopens on 2016-01-04 Mon)
- 2016-01-18 Mon Martin Luther King Day
- 2016-02-15 Mon President’s Day
- 2016-03-25 Fri  Easter Weekend
- 2016-05-30 Mon Memorial Day
- 2016-07-04 Mon 4^{th} of July
- Summer Vacation – TBD

If you need care during one of the holidays, I may be able to provide care if it has been arranged in advance.

Additionally: 5 sick days per year only taken if too ill/contagious to provide care


* Monthly Fees

- 2 days / week = 1200
- 3 days / week = 1350
- 4 days / week = 1500
- 5 days / week = 1650


- extra days : 85

I currently do not provide half days. Some parents drop their children off a little later or pick them up earlier, which is fine.

* Forms

The contract is [[../data/Thousand%20Oaks%20Childcare.pdf][available for download]].
