#+TITLE: Food
#+OPTIONS: toc:nil num:nil

I provide primarily organic, locally grown fresh foods for lunch and
snacks. The kids pick and eat vegetables and fruits from the yard, which
include green beans, fava beans, tomatoes, cucumbers, strawberries,
plums, apricots, figs, peaches, apples, asian pears and others depending on the season.  A
typical meal could include cheese, pasta, quesadillas, brown rice and
beans, and seasonal vegetables and fruits. For snacks in the morning, I
often provide oatmeal and milk or soft-boiled eggs with toast. I try to
offer each child some of their favorite foods, in addition to providing
new foods for them to try and expand their palate. We all sit at the
table to eat lunch together, which encourages the children to try new
foods as they see others eating them as well. We sing songs or discuss
whatever games we have played in the morning while they have their
meal. I also adapt the meals to accommodate dietary restrictions and
allergies. Food is included in the cost of the program.
